const EnglishData = [
    {
        id:1,
        imgsrc: "webdesign.jpg",
        heading: "Web Design for Everybody: Basics of Web Development & Coding",
        paragraph:"University of Michigan",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
          
      },
      {
        id:2,
        imgsrc: "img2.jfif",
         heading: "HTML, CSS, and Javascript for Web Developers",
        paragraph:"Johns Hopkins University",
        btn:"COURSE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:3,
        imgsrc: "img3.jfif",
        heading: "Full-Stack Web Development with React",
        paragraph:"The Hong Kong University of Science and Technology",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:4,
        imgsrc:"img4.jpg",
        heading:"Introduction to Web Development",
        paragraph:"University of California, Davis",
        btn:"COURSE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:5,
        imgsrc:"img5.jpg",
        heading:"IBM Full Stack Cloud Developer",
        paragraph:"IBM",
        btn:"PROFESSIONAL CERTIFICATE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:6,
        imgsrc:"img7.jpg",
        heading:"Full Stack Web Development with Angular",
        paragraph:"The Hong Kong University of Science and Technology",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },

      {
        id:8,
        imgsrc:"img8.jfif",
        heading:"Web Applications for Everybody",
        paragraph:"University of Michigan",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:7,
        imgsrc:"img6.jpg",
        heading:"Responsive Website Development and Design",
        paragraph:"Goldsmith, University of London",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:10,
        imgsrc:"img10.jpg",
        heading:"Google IT Support",
        paragraph:"Google",
        btn:"PROFESSIONAL CERTIFICATE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },

      {
        id:9,
        imgsrc:"img9.jpg",
        heading:"Django for Everybody",
        paragraph:"University of Michigan",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"intermediate.png",
        level_text:"Intermediate",
      },
    ]
    export default EnglishData;