/** Array class
 * i.e.   const array=[ {1}, {2} ,{3} ];
 */
 const LevelData = [

      {
        id:2,
        imgsrc:"img4.jpg",
        heading:"Introduction to Web Development",
        paragraph:"University of California, Davis",
        btn:"COURSE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
        imgstar1:"full_star.png",
        imgstar2:"full_star.png",
        imgstar3:"full_star.png",
        imgstar4:"full_star.png",
        imgstar5:"half-star.png",
      },
      {
        id:3,
        imgsrc:"img5.jpg",
        heading:"IBM Full Stack Cloud Developer",
        paragraph:"IBM",
        btn:"PROFESSIONAL CERTIFICATE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:4,
        imgsrc:"img6.jpg",
        heading:"Responsive Website Development and Design",
        paragraph:"Goldsmith, University of London",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:5,
        imgsrc:"img10.jpg",
        heading:"Google IT Support",
        paragraph:"Google",
        btn:"PROFESSIONAL CERTIFICATE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },

      {
        id:6,
        imgsrc:"imglvl6.jpg",
        heading:"Create a Website Uisng Wordpress: Free Hosting & Subdomain",
        paragraph:"Coursera Project Network",
        btn:"GUIDED PROJECT",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:7,
        imgsrc:"imglvl7.jpg",
        heading:"Google UX Design",
        paragraph:"Google",
        btn:"PROFESSIONAL CERTIFICATE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:8,
        imgsrc:"imglvl8.jpg",
        heading:"UI / UX Design",
        paragraph:"California Institude of the Arts",
        btn:"SPECIALIZATION",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      },
      {
        id:9,
        imgsrc:"imglvl9.jpg",
        heading:"Programming Foundation with JavaScript, HTML and CSS",
        paragraph:"Duke University",
        btn:"COURSE",
        span1:"4.8",
        span2:"(11,184)",
        span3:"510K",
        span4:"students",
        imgsrc_span:"plus.png",
        level_img:"begineer.png",
        level_text:"Begineer",
      }

    
  ];
  
  export default LevelData;
  